# Form implementation generated from reading ui file 'diyetisyengiris.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class diyetisyengiris(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 637)
        Form.setStyleSheet("QWidget#Form{background-color: rgb(62, 158, 132);\n"
"border:none;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.diyetisyengiriswidget = QtWidgets.QWidget(parent=Form)
        self.diyetisyengiriswidget.setObjectName("diyetisyengiriswidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.diyetisyengiriswidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(parent=self.diyetisyengiriswidget)
        self.groupBox.setStyleSheet("QGroupBox#groupBox{\n"
"    background-image: url(:/images/lblackwolf_Make_a_169_simple_and_transparent_background_with_ve_366a338a-9c89-4586-8cab-ff21b2a2a80e-removebg-preview.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"background-color: rgb(62, 158, 132);\n"
"border:none;\n"
"\n"
"}\n"
"QGroupBox{\n"
"background-color: rgba(255, 255, 255,0);\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(500, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.ustMetin = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.ustMetin.sizePolicy().hasHeightForWidth())
        self.ustMetin.setSizePolicy(sizePolicy)
        self.ustMetin.setMinimumSize(QtCore.QSize(500, 0))
        self.ustMetin.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.ustMetin.setFont(font)
        self.ustMetin.setStyleSheet("background-color: rgb(255, 84, 87);\n"
"margin:20 75 35 75px;\n"
"border-top-right-radius:15px 15px;\n"
"border-bottom-left-radius:15px 15px;")
        self.ustMetin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ustMetin.setObjectName("ustMetin")
        self.verticalLayout_5.addWidget(self.ustMetin)
        spacerItem1 = QtWidgets.QSpacerItem(0, 126, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(800, 16777215))
        self.widget_2.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(-1, 9, -1, 2)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.kullaciAdiLE = QtWidgets.QLineEdit(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.kullaciAdiLE.sizePolicy().hasHeightForWidth())
        self.kullaciAdiLE.setSizePolicy(sizePolicy)
        self.kullaciAdiLE.setMaximumSize(QtCore.QSize(16777215, 66))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(11)
        self.kullaciAdiLE.setFont(font)
        self.kullaciAdiLE.setStyleSheet("background-color: rgba(255, 255, 255,200);\n"
"border-top-left-radius:10px 10px;\n"
"border-bottom-right-radius:10px 10px;\n"
"margin-left:40px;\n"
"margin-right:40px;\n"
"margin-top:20px;")
        self.kullaciAdiLE.setText("")
        self.kullaciAdiLE.setMaxLength(50)
        self.kullaciAdiLE.setObjectName("kullaciAdiLE")
        self.verticalLayout_3.addWidget(self.kullaciAdiLE)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(800, 16777215))
        self.widget_3.setStyleSheet("background-color: rgba(255, 255, 255,200);\n"
"margin:0 49 0 49px;\n"
"border-top-left-radius:15px;\n"
"border-bottom-right-radius:15px;")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sifreLE = QtWidgets.QLineEdit(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sifreLE.sizePolicy().hasHeightForWidth())
        self.sifreLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(11)
        self.sifreLE.setFont(font)
        self.sifreLE.setStyleSheet("border-top-left-radius:10px 10px;\n"
"border-bottom-right-radius:10px 10px;\n"
"margin-left:40px;\n"
"background-color: rgba(255, 255, 255,0);\n"
"\n"
"")
        self.sifreLE.setText("")
        self.sifreLE.setMaxLength(50)
        self.sifreLE.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.sifreLE.setObjectName("sifreLE")
        self.horizontalLayout.addWidget(self.sifreLE)
        self.sifreGoster = QtWidgets.QPushButton(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sifreGoster.sizePolicy().hasHeightForWidth())
        self.sifreGoster.setSizePolicy(sizePolicy)
        self.sifreGoster.setStyleSheet("QPushButton#pushButton{\n"
"margin:15 45 15 18px;\n"
"background-color: rgba(255, 255, 255,0);\n"
"    image: url(:/goz/Downloads/showpass2.png);\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"margin:15 45 15 18px;\n"
"background-color: rgba(255, 255, 255,0);\n"
"    image: url(:/goz/Downloads/showpass.png);\n"
"}\n"
"\n"
"")
        self.sifreGoster.setText("")
        self.sifreGoster.setFlat(False)
        self.sifreGoster.setObjectName("sifreGoster")
        self.horizontalLayout.addWidget(self.sifreGoster)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_4.setObjectName("widget_4")
        self.sifremiUnuttumBT = QtWidgets.QPushButton(parent=self.widget_4)
        self.sifremiUnuttumBT.setGeometry(QtCore.QRect(340, 10, 111, 24))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(10)
        font.setBold(True)
        self.sifremiUnuttumBT.setFont(font)
        self.sifremiUnuttumBT.setStyleSheet("QPushButton#pushButton_4{\n"
"background-color: rgba(255, 255, 255,255);\n"
"margin:0 150 0 150px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 255));\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#pushButton_4:pressed{\n"
"background-color: rgba(255, 255, 255,225);\n"
"margin-left:150px;\n"
"margin-right:150px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 255));\n"
"padding-bottom:5px;\n"
"}\n"
"")
        self.sifremiUnuttumBT.setObjectName("sifremiUnuttumBT")
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.girisButonu = QtWidgets.QPushButton(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.girisButonu.sizePolicy().hasHeightForWidth())
        self.girisButonu.setSizePolicy(sizePolicy)
        self.girisButonu.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(15)
        font.setBold(True)
        self.girisButonu.setFont(font)
        self.girisButonu.setStyleSheet("\n"
"QPushButton#pushButton_3{\n"
"background-color: rgba(255, 255, 255,255);\n"
"margin:0 150 0 150px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 255));\n"
"background-color: rgb(143, 209, 102);\n"
"border-top-right-radius:15px 15px;\n"
"border-bottom-left-radius:15px 15px;\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"background-color: rgba(255, 255, 255,255);\n"
"margin-left:150px;\n"
"margin-right:150px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 255));\n"
"background-color: rgb(217, 217, 217);\n"
"border-top-right-radius:15px 15px;\n"
"border-bottom-left-radius:15px 15px;\n"
"padding-bottom:5px;\n"
"}\n"
"")
        self.girisButonu.setObjectName("girisButonu")
        self.verticalLayout_4.addWidget(self.girisButonu)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.widget_5)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.diyetisyengiriswidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ustMetin.setText(_translate("Form", "DİYETİSYEN GİRİŞ"))
        self.kullaciAdiLE.setPlaceholderText(_translate("Form", "Kullanıcı Adı"))
        self.sifreLE.setPlaceholderText(_translate("Form", "Parola"))
        self.sifremiUnuttumBT.setText(_translate("Form", "Şifremi unuttum"))
        self.girisButonu.setText(_translate("Form", "GİRİŞ"))
