# Form implementation generated from reading ui file 'hastakayıt.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class hastakayit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(627, 589)
        Form.setStyleSheet("QWidget#Form{background-color: rgb(62, 158, 132);\n"
"border:none;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hastakayitwidget = QtWidgets.QWidget(parent=Form)
        self.hastakayitwidget.setObjectName("hastakayitwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.hastakayitwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(parent=self.hastakayitwidget)
        self.groupBox.setStyleSheet("QGroupBox#groupBox{\n"
"    background-image: url(:/images/lblackwolf_Make_a_169_simple_and_transparent_background_with_ve_366a338a-9c89-4586-8cab-ff21b2a2a80e-removebg-preview.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"background-color: rgb(62, 158, 132);\n"
"border:none;\n"
"\n"
"}\n"
"QGroupBox{\n"
"background-color: rgba(255, 255, 255,0);\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(500, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ustMetin = QtWidgets.QLabel(parent=self.widget)
        self.ustMetin.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.ustMetin.setFont(font)
        self.ustMetin.setStyleSheet("background-color: rgb(255, 84, 87);\n"
"margin:70 75 70 75px;\n"
"border-top-right-radius:15px 15px;\n"
"border-bottom-left-radius:15px 15px;")
        self.ustMetin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ustMetin.setObjectName("ustMetin")
        self.verticalLayout_5.addWidget(self.ustMetin)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(800, 16777215))
        self.widget_2.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tcLE = QtWidgets.QLineEdit(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tcLE.sizePolicy().hasHeightForWidth())
        self.tcLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(11)
        self.tcLE.setFont(font)
        self.tcLE.setStyleSheet("background-color: rgba(255, 255, 255,200);\n"
"border-top-left-radius:10px 10px;\n"
"border-bottom-right-radius:10px 10px;\n"
"margin-left:40px;\n"
"margin-right:40px;")
        self.tcLE.setText("")
        self.tcLE.setMaxLength(11)
        self.tcLE.setObjectName("tcLE")
        self.verticalLayout_3.addWidget(self.tcLE)
        self.adLE = QtWidgets.QLineEdit(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.adLE.sizePolicy().hasHeightForWidth())
        self.adLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(11)
        self.adLE.setFont(font)
        self.adLE.setStyleSheet("background-color: rgba(255, 255, 255,200);\n"
"border-top-left-radius:10px 10px;\n"
"border-bottom-right-radius:10px 10px;\n"
"margin-left:40px;\n"
"margin-right:40px;")
        self.adLE.setText("")
        self.adLE.setMaxLength(50)
        self.adLE.setObjectName("adLE")
        self.verticalLayout_3.addWidget(self.adLE)
        self.soyadLE = QtWidgets.QLineEdit(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.soyadLE.sizePolicy().hasHeightForWidth())
        self.soyadLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(11)
        self.soyadLE.setFont(font)
        self.soyadLE.setStyleSheet("background-color: rgba(255, 255, 255,200);\n"
"border-top-left-radius:10px 10px;\n"
"border-bottom-right-radius:10px 10px;\n"
"margin-left:40px;\n"
"margin-right:40px;")
        self.soyadLE.setText("")
        self.soyadLE.setMaxLength(50)
        self.soyadLE.setObjectName("soyadLE")
        self.verticalLayout_3.addWidget(self.soyadLE)
        self.emailLE = QtWidgets.QLineEdit(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.emailLE.sizePolicy().hasHeightForWidth())
        self.emailLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(11)
        self.emailLE.setFont(font)
        self.emailLE.setStyleSheet("background-color: rgba(255, 255, 255,200);\n"
"border-top-left-radius:10px 10px;\n"
"border-bottom-right-radius:10px 10px;\n"
"margin-left:40px;\n"
"margin-right:40px;")
        self.emailLE.setText("")
        self.emailLE.setMaxLength(50)
        self.emailLE.setObjectName("emailLE")
        self.verticalLayout_3.addWidget(self.emailLE)
        self.dogumTarihiLE = QtWidgets.QLineEdit(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dogumTarihiLE.sizePolicy().hasHeightForWidth())
        self.dogumTarihiLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(11)
        self.dogumTarihiLE.setFont(font)
        self.dogumTarihiLE.setStyleSheet("background-color: rgba(255, 255, 255,200);\n"
"border-top-left-radius:10px 10px;\n"
"border-bottom-right-radius:10px 10px;\n"
"margin-left:40px;\n"
"margin-right:40px;")
        self.dogumTarihiLE.setText("")
        self.dogumTarihiLE.setMaxLength(50)
        self.dogumTarihiLE.setObjectName("dogumTarihiLE")
        self.verticalLayout_3.addWidget(self.dogumTarihiLE)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_6.setStyleSheet("QWidget#widget_6{background-color: rgba(255, 255, 255,200);\n"
"\n"
"margin:0 40 0 40px;\n"
"border-top-left-radius:10px 10px;\n"
"border-bottom-right-radius:10px 10px;}\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(11)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color: rgb(127, 127, 150);\n"
"margin-left:31px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cinsiyetCB = QtWidgets.QComboBox(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cinsiyetCB.sizePolicy().hasHeightForWidth())
        self.cinsiyetCB.setSizePolicy(sizePolicy)
        self.cinsiyetCB.setStyleSheet("background-color: rgba(207, 207, 207,70);\n"
"color: rgb(0, 0, 0);")
        self.cinsiyetCB.setObjectName("cinsiyetCB")
        self.cinsiyetCB.addItem("")
        self.cinsiyetCB.addItem("")
        self.horizontalLayout_2.addWidget(self.cinsiyetCB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(800, 16777215))
        self.widget_7.setStyleSheet("background-color: rgba(255, 255, 255,200);\n"
"margin:0 40 10 40px;\n"
"border-top-left-radius:15px;\n"
"border-bottom-right-radius:15px;")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.parolaLE = QtWidgets.QLineEdit(parent=self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.parolaLE.sizePolicy().hasHeightForWidth())
        self.parolaLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(11)
        self.parolaLE.setFont(font)
        self.parolaLE.setStyleSheet("border-top-left-radius:10px 10px;\n"
"border-bottom-right-radius:10px 10px;\n"
"margin-left:40px;\n"
"background-color: rgba(255, 255, 255,0);\n"
"\n"
"")
        self.parolaLE.setText("")
        self.parolaLE.setMaxLength(50)
        self.parolaLE.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.parolaLE.setObjectName("parolaLE")
        self.horizontalLayout_3.addWidget(self.parolaLE)
        self.sifreGoster = QtWidgets.QPushButton(parent=self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sifreGoster.sizePolicy().hasHeightForWidth())
        self.sifreGoster.setSizePolicy(sizePolicy)
        self.sifreGoster.setStyleSheet("QPushButton#pushButton{\n"
"margin:15 45 15 18px;\n"
"background-color: rgba(255, 255, 255,0);\n"
"    image: url(:/goz/Downloads/showpass2.png);\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"margin:15 45 15 18px;\n"
"background-color: rgba(255, 255, 255,0);\n"
"    image: url(:/goz/Downloads/showpass.png);\n"
"}\n"
"\n"
"")
        self.sifreGoster.setText("")
        self.sifreGoster.setFlat(False)
        self.sifreGoster.setObjectName("sifreGoster")
        self.horizontalLayout_3.addWidget(self.sifreGoster)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(800, 16777215))
        self.widget_3.setStyleSheet("background-color: rgba(255, 255, 255,200);\n"
"margin:0 49 0 49px;\n"
"border-top-left-radius:15px;\n"
"border-bottom-right-radius:15px;")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.kaydolBT = QtWidgets.QPushButton(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.kaydolBT.sizePolicy().hasHeightForWidth())
        self.kaydolBT.setSizePolicy(sizePolicy)
        self.kaydolBT.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(15)
        font.setBold(True)
        self.kaydolBT.setFont(font)
        self.kaydolBT.setStyleSheet("\n"
"QPushButton#pushButton_2{\n"
"background-color: rgb(143, 209, 102);\n"
"margin:15 150 15 150px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 255));\n"
"background-color: rgb(143, 209, 102);\n"
"border-top-right-radius:15px 15px;\n"
"border-bottom-left-radius:15px 15px;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"background-color: rgba(255, 255, 255,255);\n"
"margin-left:150px;\n"
"margin-right:150px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 255));\n"
"background-color: rgb(217, 217, 217);\n"
"border-top-right-radius:15px 15px;\n"
"border-bottom-left-radius:15px 15px;\n"
"padding-bottom:5px;\n"
"}\n"
"")
        self.kaydolBT.setObjectName("kaydolBT")
        self.verticalLayout_4.addWidget(self.kaydolBT)
        self.verticalLayout.addWidget(self.widget_5)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.hastakayitwidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ustMetin.setText(_translate("Form", "HASTA KAYIT"))
        self.tcLE.setPlaceholderText(_translate("Form", "T.C. Kimlik No"))
        self.adLE.setPlaceholderText(_translate("Form", "Ad"))
        self.soyadLE.setPlaceholderText(_translate("Form", "Soyad"))
        self.emailLE.setPlaceholderText(_translate("Form", "E-posta Adresi"))
        self.dogumTarihiLE.setPlaceholderText(_translate("Form", "Doğum Tarihi"))
        self.label_2.setText(_translate("Form", "Cinsiyet"))
        self.cinsiyetCB.setItemText(0, _translate("Form", "    Kadın"))
        self.cinsiyetCB.setItemText(1, _translate("Form", "    Erkek"))
        self.parolaLE.setPlaceholderText(_translate("Form", "Parola"))
        self.kaydolBT.setText(_translate("Form", "KAYDOL"))
